- name: Install nginx
  apt:
    name: nginx
    state: present
    cache_valid_time: "{{ apt_cache_time }}"

- name: Upload site configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    validate: "nginx -t -c /etc/nginx/nginx.conf -p %s"
  notify:
    - reload nginx

- name: Enable site
  file:
    src: "{{ nginx_conf_path }}"
    dest: "{{ nginx_conf_enabled_path }}"
    state: link
  notify:
    - reload nginx
