- name: Create celery user
  user:
    name: "{{ celery_user }}"
    group: "{{ celery_user_group | default(omit) }}"
    createhome: no

- name: Create Celery directory config
  template:
    src: celery-tempfiles.conf.j2
    dest: /etc/tmpfiles.d/celery.conf

- name: Upload celery service config
  template:
    src: celery.service.j2
    dest: "{{ celery_service_conf }}"
  notify:
    - reload celery

- name: Start and enable the celery service
  systemd:
    name: celery
    state: started
    enabled: yes
    daemon-reload: yes
