- name: Create celery user
  user:
    name: "{{ celery_user }}"
    group: "{{ celery_user_group | default(omit) }}"
    createhome: no

- name: Set permissions for celery dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ celery_user }}"
    group: "{{ celery_user_group | default(omit) }}"
    recurse: yes
  with_items:
    - "{{ celeryd_log_dir }}"
    - "{{ celeryd_pid_dir }}"

- name: Upload celery service config
  template:
    src: celery.service.j2
    dest: "{{ celery_service_conf }}"
  notify:
    - reload celery

- name: Start and enable the celery service
  systemd:
    name: celery
    state: started
    enabled: yes
    daemon-reload: yes
