- name: Create logging dir
  file:
    path: "{{ django_log_file | dirname }}"
    state: directory
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_user_group }}"
    recurse: yes
  when: django_log_file is defined and django_log_file

- name: Create log file with correct permissions
  file:
    path: "{{ django_log_file }}"
    state: touch
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_user_group | default(omit) }}"
  when: django_log_file is defined and django_log_file

- name: Upload local settings file
  template:
    src: local_settings.py.j2
    dest: "{{ django_local_settings }}"
  notify:
    - reload celery
    - restart gunicorn

- name: Run Django migrations
  django_manage:
    command: migrate
    app_path: "{{ django_app_path }}"
    virtualenv: "{{ virtualenv }}"
  notify:
    - reload celery
    - restart gunicorn

- name: Compile SCSS
  django_manage:
    command: compilescss
    app_path: "{{ django_app_path }}"
    virtualenv: "{{ virtualenv }}"

- name: Collect static files
  django_manage:
    command: collectstatic -i *.scss --noinput
    app_path: "{{ django_app_path }}"
    virtualenv: "{{ virtualenv }}"
