# General
deploy_user: deploy

admin_name: Chathan
admin_email: "chathan@driehuys.com"

# Users who should be in the `docker` group which grants them access to `docker`
# commands without sudo use.
docker_users:
  - "{{ deploy_user }}"

chmvh_docker_network:
  name: chmvh

docker_networks:
  - "{{ chmvh_docker_network }}"

traefik_networks:
  - "{{ chmvh_docker_network }}"

# Global pip packages
pip_install_packages:
  - docker
  - psycopg2-binary

# Web settings
chmvh_hosts: "{{ [inventory_hostname] + additional_hosts }}"

letsencrypt_email: "{{ admin_email }}"

traefik_published_ports:
  - 80:80
  - 443:443
