# Global
app_dir: /opt/chmvh-website
app_repo: https://github.com/cdriehuys/chmvh-website

service_group: appservices

apt_cache_time: 3600

# Security
deploy_user: sysadmin
deploy_user_primary_group: null
deploy_user_public_key_files:
  - ~/.ssh/id_rsa.pub

deploy_groups:
  - "{{ service_group }}"

ufw_enabled_ports:
  web_traffic:
    port: www
    proto: any
  secure_web_traffic:
    port: 443
    proto: tcp

# Database
db_user: django

postgresql_service_group: "{{ service_group }}"
postgresql_databases:
  - name: chmvh-website
    owner: django
postgresql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_password }}"
    encrypted: no

# Letsencrypt
letsencrypt_email: cdriehuys@gmail.com
letsencrypt_renew_hour: 2
letsencrypt_renew_minute: 7
letsencrypt_renew_pre_hook: systemctl stop nginx
letsencrypt_renew_post_hook: systemctl start nginx

# NGINX
nginx_site_conf_name: chmvh-website.conf
nginx_user: nginx
nginx_user_groups:
  - "{{ service_group }}"
nginx_webroot: /var/www/{{ inventory_hostname }}

nginx_servers:
  - listen: 80
    name: "{{ inventory_hostname }}"
    extra_params: |
      return 301 https://$server_name$request_uri;
  - listen: 443 ssl http2
    name: "{{ inventory_hostname }}"
    extra_params: |
      ssl_certificate {{ letsencrypt_live_dir }}/fullchain.pem;
      ssl_certificate_key {{ letsencrypt_live_dir }}/privkey.pem;

      # from https://cipherli.st/
      # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_prefer_server_ciphers on;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
      ssl_ecdh_curve secp384r1;
      ssl_session_cache shared:SSL:10m;
      ssl_session_tickets off;
      ssl_stapling on;
      ssl_stapling_verify on;
      resolver 8.8.8.8 8.8.4.4 valid=300s;
      resolver_timeout 5s;
      # Disable preloading HSTS for now.  You can use the commented out header line that includes
      # the "preload" directive if you understand the implications.
      #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
      add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;

      ssl_dhparam {{ letsencrypt_dh_group }};

# App Settings
virtualenv: /opt/virtualenvs/chmvh-website
virtualenv_python: python3

app_extra_packages:
  - libjpeg-dev
  - libpq-dev
  - python3
  - python3-dev
  - python3-pip
  - zlib1g-dev
