# First ensure that python is installed on the remote machine
# Source: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
- hosts: all
  remote_user: root
  gather_facts: False

  tasks:
  - name: Install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when: output.stdout != ""

- include: security.yml
- include: webservers.yml
