- hosts: all
  become: yes
  become_user: root
  remote_user: "{{ deploy_user }}"

  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}-vault.yml

  roles:
    - ANXS.postgresql
    - letsencrypt
    - nginx
    - django-app

