---
- name: Test root connection
  ansible.builtin.ping:
  changed_when: "False"
  ignore_unreachable: true
  register: root_ping

- include:
    file: create-deploy-user.yml
  when: "'unreachable' in root_ping and root_ping.unreachable'"
