app_dir: /opt/app
app_repo_branch: master
app_packages:
  - git
  - python-pip
app_extra_packages: []

virtualenv: /opt/virtualenvs/env
virtualenv_python: python2
virtualenv_requirements: "{{ app_dir }}/requirements.txt"
