name: Review Build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requirements
        run: pip install -r dev-requirements.txt

      - name: Check style
        run: black --check .

      - name: Lint code
        run: flake8 .

      - name: Run tests
        run: pytest chmvh_website/
        env:
          CHMVH_SECRET_KEY: test
